[package]
name = "cosmian_findex_memories"
version = "7.1.0"
authors = [
    "Emmanuel Coste <emmanuel.coste@cosmian.com>",
    "Hatem Mnaouer <hatem.mnaouer@cosmian.com>",
    "Théophile Brézot <theophile.brezot@cosmian.com>",
]
categories = ["cryptography"]
edition = "2021"
keywords = ["SSE"]
license = "BUSL-1.1"
repository = "https://github.com/Cosmian/findex-memories/"
description = "Symmetric Searchable Encryption"

[lib]
name = "cosmian_findex_memories"
path = "src/lib.rs"

[features]
default = ["redis-mem"]
redis-mem = ["redis"]
sqlite-mem = ["async-sqlite"]
postgres-mem = ["tokio-postgres", "tokio", "deadpool-postgres"]

[dependencies]
cosmian_crypto_core = { version = "10.1", default-features = false, features = [
    "macro",
    "sha3",
] }
cosmian_findex = { version = "7.1.0" }
# Due to dependency tree issues with sqlx requiring a lower version of `libsqlite3-sys`, do not upgrade the `async-sqlite` version above 0.4
# before checking the update will not break findex-server's build.
async-sqlite = { version = "0.4", optional = true }
deadpool-postgres = { version = "0.14.1", optional = true }
redis = { version = "0.31", features = [
    "aio",
    "connection-manager",
    "tokio-comp",
], optional = true }
tokio-postgres = { version = "0.7.9", optional = true, features = [
    "array-impls",
] }
tokio = { version = "1.44", optional = true }


[dev-dependencies]
tokio = { version = "1.44", features = ["macros", "rt-multi-thread"] }

# TODO: keep this ?
# [[bench]]
# name = "benches"
# harness = false
# required-features = ["test-utils"]
